name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        bun-version: [latest, canary]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Bun ${{ matrix.bun-version }}
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ matrix.bun-version }}
    
    - name: Install dependencies
      run: bun install
    
    - name: Lint code
      run: bun run lint
    
    - name: Build project
      run: bun run build
    
    - name: Test CLI with Bun
      run: bun run test
    
    - name: Test built package with Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Verify Node.js compatibility
      run: node dist/index.js --help
    
    - name: Test generate command
      run: |
        mkdir test-project
        cd test-project
        node ../dist/index.js init --name test-bot --template typescript --bot-type general --dotenv --commands --slash
        ls -la
        cat package.json

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Install dependencies
      run: bun install
    
    - name: Build
      run: bun run build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
